### ISSUE TITLE
Draw Design on Screens

### ISSUE THREAD

**Issue by ARUIZVASQUEZ** [mdunlavy/VotingScreen#1]
Admin Screen
- Capabilities
    - Shutting machine off
    - Turning Voting Session On/Off
    - Ejecting
        - Ballot SD
        - Votes SD 1
        - Votes SD 2
        
User Screen(s)
- Waiting For Ticket Screen
- Intro to Ballot Screen
- Proposition Screens
- Confirmation Screen

**Comment by mdunlavy** [comment]
first draft finished - pushed to main and named "screenDesignV1"
