### ISSUE TITLE
Admin Screen

### ISSUE THREAD

**Issue by ARUIZVASQUEZ** [mdunlavy/VotingScreen#6]
Will be a pop up screen from the welcome screen similar to the confirmation pop up screen
Should be able to
- [x] Buttons
      - [ ] Pause Voting - Pauses session temporarily (at night when the voting center closes)
      - [ ] Start Voting - Resumes session or starts new session
      - [ ] Stop Voting - Permanently closes voting, once election is over

**Comment by hhuang131** [comment]
admin screen completed and added "admin mode" button at the top of the welcome screen and voting screen
start button functionality: set unlock to true and jump to welcome screen, user is able to begin election (assume ballot is set)
stop button and pause button functionality: set unlock to false and jump to welcome screen, user is not able to begin election
implemented admin execute instruction pop up confirmation window
implemented admin login pop up window and invalid username/password alert window
(now the valid username and valid password is set as: adminTest, 123456)
